# Generated by Django 5.1.5 on 2025-02-10 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='selleruser',
            table='seller_selleruser',
        ),
    ]
