# Generated by Django 5.1.5 on 2025-02-10 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_alter_selleruser_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='selleruser',
            table=None,
        ),
    ]
