# Generated by Django 5.1.5 on 2025-02-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_products_stripe_price_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
