# Generated by Django 5.1.5 on 2025-02-07 19:39

import django.db.models.deletion
import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_products_stock'),
        ('user', '0009_remove_selleruser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='user.selleruser', null=True),
        ),
    ]
