# Generated by Django 5.1.5 on 2025-02-07 19:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='opinion',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
