# Generated by Django 5.1.5 on 2025-02-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion & Clothing'), ('home_garden', 'Home & Garden'), ('health_beauty', 'Health & Beauty'), ('toys', 'Toys & Kids'), ('sports', 'Sports & Recreation'), ('automotive', 'Automotive'), ('supermarket', 'Supermarket'), ('books', 'Books & Media'), ('pets', 'Pets'), ('office_school', 'Office & School Supplies')], max_length=255),
        ),
    ]
