# Generated by Django 5.1.5 on 2025-01-27 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('address', models.CharField(max_length=300)),
                ('phone_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(999999999999999)])),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=200, null=True)),
                ('zip', models.CharField(max_length=9)),
                ('preparing', models.BooleanField(null=True)),
                ('on_the_way', models.BooleanField(null=True)),
                ('delivered', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
