# Generated by Django 5.1.5 on 2025-01-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_address_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='email_address',
            field=models.CharField(max_length=254),
        ),
    ]
