# Generated by Django 5.1.5 on 2025-01-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_promocode_value_order_orderitem_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='times_of_use',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
