# Generated by Django 5.1.5 on 2025-01-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_promocode_times_of_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='times_of_use',
            field=models.IntegerField(default=0),
        ),
    ]
