# Generated by Django 5.1.5 on 2025-01-31 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_promocode_times_of_use'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='times_of_use',
        ),
    ]
