# Generated by Django 5.1.5 on 2025-02-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_alter_transaction_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id_transaction',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
