# Generated by Django 5.1.5 on 2025-02-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_alter_transaction_id_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='Washington', max_length=200),
        ),
    ]
