# Generated by Django 5.1.5 on 2025-02-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_selleruser_seller_selleruser_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selleruser',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='selleruser',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='selleruser',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='selleruser',
            name='tax_id',
            field=models.CharField(max_length=15),
        ),
    ]
