# Generated by Django 5.1.5 on 2025-02-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_selleruser_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleruser',
            name='email',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
