# Generated by Django 5.1.5 on 2025-02-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_selleruser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selleruser',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
