# Generated by Django 5.1.5 on 2025-02-07 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_selleruser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selleruser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='selleruser',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='selleruser',
            name='tax_id',
        ),
    ]
