# Generated by Django 5.1.5 on 2025-02-07 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_selleruser_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selleruser',
            name='email',
        ),
    ]
